services:
  web:
    build: .
    command: gunicorn BellzStudio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"  
    env_file:
      - .env 
    depends_on:
      - redis
    networks:
      - bellz_network

  celery:
    build: .
    command: ["celery", "-A", "BellzStudio", "worker", "--uid=celeryuser", "--loglevel=info"] # celery -A BellzStudio worker --loglevel=info
    volumes:
      - .:/var/www
    depends_on:
      - web
      - redis
    env_file:
      - .env  
    networks:
      - bellz_network

  celery-beat:
    build: .
    command:  
    volumes:
      - .:/var/www
    depends_on:
      - celery
      - redis
    env_file:
      - .env 
    networks:
      - bellz_network

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - bellz_network

networks:
  bellz_network:
    driver: bridge
